"""final model alignment without unique username

Revision ID: 0cce95996e99
Revises: e8be6e260d2f
Create Date: 2026-04-08 22:38:45.537348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cce95996e99'
down_revision = 'e8be6e260d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_announcement_created_by_id'))
        batch_op.create_index(batch_op.f('ix_announcement_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dish_created_by_id'))
        batch_op.create_index(batch_op.f('ix_dish_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_expense_budget_id'))
        batch_op.drop_index(batch_op.f('idx_expense_user_id'))
        batch_op.create_index(batch_op.f('ix_expense_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_feedback_menu_id'))
        batch_op.drop_index(batch_op.f('idx_feedback_user_id'))
        batch_op.create_index(batch_op.f('ix_feedback_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('floor_lend_borrow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_floor_lend_borrow_created_by_id'))
        batch_op.create_index(batch_op.f('ix_floor_lend_borrow_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('garamat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_garamat_created_by_id'))
        batch_op.drop_index(batch_op.f('idx_garamat_team_id'))
        batch_op.drop_index(batch_op.f('idx_garamat_user_id'))
        batch_op.create_index(batch_op.f('ix_garamat_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garamat_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garamat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_menu_assigned_team_id'))
        batch_op.drop_index(batch_op.f('idx_menu_assigned_to_id'))
        batch_op.drop_index(batch_op.f('idx_menu_created_by_id'))
        batch_op.drop_index(batch_op.f('idx_menu_dish_id'))
        batch_op.create_index(batch_op.f('ix_menu_assigned_team_id'), ['assigned_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_dish_id'), ['dish_id'], unique=False)

    with op.batch_alter_table('platform_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_platform_audits_performed_by_id'))
        batch_op.create_index(batch_op.f('ix_platform_audits_performed_by_id'), ['performed_by_id'], unique=False)

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_procurement_item_assigned_to_id'))
        batch_op.drop_index(batch_op.f('idx_procurement_item_bill_id'))
        batch_op.drop_index(batch_op.f('idx_procurement_item_created_by_id'))
        batch_op.create_index(batch_op.f('ix_procurement_item_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_item_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_item_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_push_subscription_user_id'))
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_request_approved_by_id'))
        batch_op.drop_index(batch_op.f('idx_request_user_id'))
        batch_op.create_index(batch_op.f('ix_request_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('special_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_special_event_created_by_id'))
        batch_op.create_index(batch_op.f('ix_special_event_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_suggestion_user_id'))
        batch_op.create_index(batch_op.f('ix_suggestion_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'dish', ['dish_id'], ['id'])

    with op.batch_alter_table('suggestion_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_suggestion_vote_suggestion_id'))
        batch_op.drop_index(batch_op.f('idx_suggestion_vote_user_id'))
        batch_op.create_index(batch_op.f('ix_suggestion_vote_suggestion_id'), ['suggestion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestion_vote_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tea_task_assigned_to_id'))
        batch_op.drop_index(batch_op.f('idx_tea_task_created_by_id'))
        batch_op.create_index(batch_op.f('ix_tea_task_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tea_task_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_created_by_id'))
        batch_op.create_index(batch_op.f('ix_team_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_member_team_id'))
        batch_op.drop_index(batch_op.f('idx_team_member_user_id'))
        batch_op.create_index(batch_op.f('ix_team_member_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_team_id'))
        batch_op.create_index(batch_op.f('idx_team_member_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_team_member_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_created_by_id'))
        batch_op.create_index(batch_op.f('idx_team_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tea_task_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_tea_task_assigned_to_id'))
        batch_op.create_index(batch_op.f('idx_tea_task_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tea_task_assigned_to_id'), ['assigned_to_id'], unique=False)

    with op.batch_alter_table('suggestion_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_suggestion_vote_suggestion_id'))
        batch_op.create_index(batch_op.f('idx_suggestion_vote_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_suggestion_vote_suggestion_id'), ['suggestion_id'], unique=False)

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suggestion_user_id'))
        batch_op.create_index(batch_op.f('idx_suggestion_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('special_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_special_event_created_by_id'))
        batch_op.create_index(batch_op.f('idx_special_event_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_approved_by_id'))
        batch_op.create_index(batch_op.f('idx_request_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_request_approved_by_id'), ['approved_by_id'], unique=False)

    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))
        batch_op.create_index(batch_op.f('idx_push_subscription_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_item_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_item_bill_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_item_assigned_to_id'))
        batch_op.create_index(batch_op.f('idx_procurement_item_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_procurement_item_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_procurement_item_assigned_to_id'), ['assigned_to_id'], unique=False)

    with op.batch_alter_table('platform_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_audits_performed_by_id'))
        batch_op.create_index(batch_op.f('idx_platform_audits_performed_by_id'), ['performed_by_id'], unique=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_dish_id'))
        batch_op.drop_index(batch_op.f('ix_menu_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_menu_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_menu_assigned_team_id'))
        batch_op.create_index(batch_op.f('idx_menu_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_menu_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_menu_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_menu_assigned_team_id'), ['assigned_team_id'], unique=False)

    with op.batch_alter_table('garamat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garamat_user_id'))
        batch_op.drop_index(batch_op.f('ix_garamat_team_id'))
        batch_op.drop_index(batch_op.f('ix_garamat_created_by_id'))
        batch_op.create_index(batch_op.f('idx_garamat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_garamat_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_garamat_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('floor_lend_borrow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floor_lend_borrow_created_by_id'))
        batch_op.create_index(batch_op.f('idx_floor_lend_borrow_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_menu_id'))
        batch_op.create_index(batch_op.f('idx_feedback_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_feedback_menu_id'), ['menu_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_budget_id'))
        batch_op.create_index(batch_op.f('idx_expense_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_expense_budget_id'), ['budget_id'], unique=False)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_created_by_id'))
        batch_op.create_index(batch_op.f('idx_dish_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_created_by_id'))
        batch_op.create_index(batch_op.f('idx_announcement_created_by_id'), ['created_by_id'], unique=False)

    # ### end Alembic commands ###
