"""Add composite indexes for tenant_id and floor

Revision ID: 3f8cf96330f8
Revises: 0cce95996e99
Create Date: 2026-04-09 07:37:06.908998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8cf96330f8'
down_revision = '0cce95996e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_index('idx_bill_tenant_floor', ['tenant_id', 'floor'], unique=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index('idx_budget_tenant_floor', ['tenant_id', 'floor'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index('idx_expense_tenant_floor_date', ['tenant_id', 'floor', 'date'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_tenant_floor', ['tenant_id', 'floor'], unique=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_menu_rotation'))
        batch_op.create_index('idx_menu_tenant_floor_date', ['tenant_id', 'floor', 'date', 'is_buffer', 'assigned_team_id'], unique=False)

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.create_index('idx_procurement_tenant_floor_status', ['tenant_id', 'floor', 'status'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index('idx_request_tenant_floor_status', ['tenant_id', 'floor', 'status'], unique=False)

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index('idx_suggestion_tenant_floor', ['tenant_id', 'floor'], unique=False)

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.create_index('idx_teatask_tenant_floor_date', ['tenant_id', 'floor', 'date'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index('idx_team_tenant_floor', ['tenant_id', 'floor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('idx_team_tenant_floor')

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.drop_index('idx_teatask_tenant_floor_date')

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index('idx_suggestion_tenant_floor')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index('idx_request_tenant_floor_status')

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.drop_index('idx_procurement_tenant_floor_status')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index('idx_menu_tenant_floor_date')
        batch_op.create_index(batch_op.f('idx_menu_rotation'), ['floor', 'date', 'is_buffer', 'assigned_team_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_tenant_floor')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index('idx_expense_tenant_floor_date')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index('idx_budget_tenant_floor')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index('idx_bill_tenant_floor')

    # ### end Alembic commands ###
