"""Add pdf storage columns to ExpensePrintReport

Revision ID: 8ee30d5a76d9
Revises: 3f8cf96330f8
Create Date: 2026-04-16 01:18:49.335539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee30d5a76d9'
down_revision = '3f8cf96330f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_print_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('storage_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_print_report', schema=None) as batch_op:
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('storage_path')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('stored_filename')

    # ### end Alembic commands ###
