"""add menu suggestion table

Revision ID: a8b8d291b3c7
Revises: c6d7e8f9a0b1
Create Date: 2026-06-08 07:35:48.537280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b8d291b3c7'
down_revision = 'c6d7e8f9a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('new_dish_name', sa.String(length=100), nullable=True),
    sa.Column('side_dish_id', sa.Integer(), nullable=True),
    sa.Column('new_side_dish_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suggested_team_id', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('suggested_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['side_dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['suggested_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['suggested_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_suggestion', schema=None) as batch_op:
        batch_op.create_index('idx_menusuggestion_tenant_floor_date', ['tenant_id', 'floor', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_suggestion_suggested_by_id'), ['suggested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_suggestion_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_tenant_id'))
        batch_op.drop_constraint(batch_op.f('dish_tenant_id_fkey'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('dish_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_dish_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('menu_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_suggestion_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_menu_suggestion_suggested_by_id'))
        batch_op.drop_index('idx_menusuggestion_tenant_floor_date')

    op.drop_table('menu_suggestion')
    # ### end Alembic commands ###
