"""initial migration

Revision ID: bdd4590fc68f
Revises: 
Create Date: 2026-02-25 09:11:26.596143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdd4590fc68f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_announcement_tenant_id'))
        batch_op.create_index(batch_op.f('ix_announcement_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bill_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bill_source'))
        batch_op.create_index(batch_op.f('ix_bill_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_budget_tenant_id'))
        batch_op.create_index(batch_op.f('ix_budget_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('dish_name_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_dish_tenant_id'))
        batch_op.drop_index(batch_op.f('uq_dish_name_lower'))
        batch_op.create_index(batch_op.f('ix_dish_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_expense_tenant_id'))
        batch_op.create_index(batch_op.f('ix_expense_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_feedback_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_menu_id'))
        batch_op.create_index(batch_op.f('ix_feedback_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('feedback_menu_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['menu_id'], ['id'])

    with op.batch_alter_table('floor_lend_borrow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_floor_lend_borrow_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lend_borrow_borrower'))
        batch_op.drop_index(batch_op.f('ix_lend_borrow_lender'))
        batch_op.drop_index(batch_op.f('ix_lend_borrow_status'))
        batch_op.create_index(batch_op.f('ix_floor_lend_borrow_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('garamat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_garamat_tenant_id'))
        batch_op.create_index(batch_op.f('ix_garamat_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_menu_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_menu_assigned_team_id'))
        batch_op.drop_index(batch_op.f('ix_menu_dish_id'))
        batch_op.create_index(batch_op.f('ix_menu_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('menu_dish_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('menu_assigned_team_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dish', ['dish_id'], ['id'])
        batch_op.create_foreign_key(None, 'team', ['assigned_team_id'], ['id'])

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.alter_column('expense_recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_procurement_item_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_item_bill_id'))
        batch_op.create_index(batch_op.f('ix_procurement_item_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('procurement_item_bill_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_request_tenant_id'))
        batch_op.create_index(batch_op.f('ix_request_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('special_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_special_event_tenant_id'))
        batch_op.create_index(batch_op.f('ix_special_event_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_suggestion_tenant_id'))
        batch_op.create_index(batch_op.f('ix_suggestion_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('suggestion_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_suggestion_vote_tenant_id'))
        batch_op.create_index(batch_op.f('ix_suggestion_vote_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tea_task_tenant_id'))
        batch_op.create_index(batch_op.f('ix_tea_task_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_team_floor'))
        batch_op.drop_index(batch_op.f('uq_team_floor_name'))
        batch_op.create_index(batch_op.f('ix_team_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_team_member_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_user_id'))
        batch_op.drop_index(batch_op.f('uq_team_member_team_user'))
        batch_op.create_index(batch_op.f('ix_team_member_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_tenant_id'))
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(None, ['tr_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))
        batch_op.create_index(batch_op.f('idx_user_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_tenant_id'))
        batch_op.create_index(batch_op.f('uq_team_member_team_user'), ['team_id', 'user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_member_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_team_member_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_tenant_id'))
        batch_op.create_index(batch_op.f('uq_team_floor_name'), ['floor', 'name'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('idx_team_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tea_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tea_task_tenant_id'))
        batch_op.create_index(batch_op.f('idx_tea_task_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('suggestion_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_vote_tenant_id'))
        batch_op.create_index(batch_op.f('idx_suggestion_vote_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_tenant_id'))
        batch_op.create_index(batch_op.f('idx_suggestion_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('special_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_special_event_tenant_id'))
        batch_op.create_index(batch_op.f('idx_special_event_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_tenant_id'))
        batch_op.create_index(batch_op.f('idx_request_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('procurement_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('procurement_item_bill_id_fkey'), 'bill', ['bill_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_procurement_item_tenant_id'))
        batch_op.create_index(batch_op.f('ix_procurement_item_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_procurement_item_tenant_id'), ['tenant_id'], unique=False)
        batch_op.alter_column('expense_recorded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('menu_assigned_team_id_fkey'), 'team', ['assigned_team_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('menu_dish_id_fkey'), 'dish', ['dish_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_menu_tenant_id'))
        batch_op.create_index(batch_op.f('ix_menu_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_assigned_team_id'), ['assigned_team_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_menu_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('garamat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garamat_tenant_id'))
        batch_op.create_index(batch_op.f('idx_garamat_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('floor_lend_borrow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floor_lend_borrow_tenant_id'))
        batch_op.create_index(batch_op.f('ix_lend_borrow_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lend_borrow_lender'), ['lender_floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_lend_borrow_borrower'), ['borrower_floor'], unique=False)
        batch_op.create_index(batch_op.f('idx_floor_lend_borrow_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_menu_id_fkey'), 'menu', ['menu_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_feedback_tenant_id'))
        batch_op.create_index(batch_op.f('ix_feedback_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_feedback_tenant_id'), ['tenant_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_tenant_id'))
        batch_op.create_index(batch_op.f('idx_expense_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_tenant_id'))
        batch_op.create_index(batch_op.f('uq_dish_name_lower'), [sa.literal_column('lower(name::text)')], unique=True)
        batch_op.create_index(batch_op.f('idx_dish_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('dish_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_tenant_id'))
        batch_op.create_index(batch_op.f('idx_budget_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_tenant_id'))
        batch_op.create_index(batch_op.f('ix_bill_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('idx_bill_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_tenant_id'))
        batch_op.create_index(batch_op.f('idx_announcement_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
