"""add dish_champion table

Revision ID: bf70982c9399
Revises: a8b8d291b3c7
Create Date: 2026-07-01 18:03:35.034214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf70982c9399'
down_revision = 'a8b8d291b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'team_id', 'dish_id', name='uq_tenant_team_dish_champion')
    )
    with op.batch_alter_table('dish_champion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_champion_dish_id'), ['dish_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dish_champion_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dish_champion_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_champion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_champion_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_dish_champion_team_id'))
        batch_op.drop_index(batch_op.f('ix_dish_champion_dish_id'))

    op.drop_table('dish_champion')
    # ### end Alembic commands ###
