"""add_room_rotation_tables

Revision ID: da3aec7ee317
Revises: bf70982c9399
Create Date: 2026-07-01 19:30:24.297424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3aec7ee317'
down_revision = 'bf70982c9399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_rotation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('waari_count', sa.Integer(), nullable=False),
    sa.Column('active_days_mask', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_rotation_settings', schema=None) as batch_op:
        batch_op.create_index('idx_rotation_settings_tenant_floor', ['tenant_id', 'floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_rotation_settings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('room_rotation_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.String(length=20), nullable=False),
    sa.Column('override_team_id', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['override_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_rotation_exception', schema=None) as batch_op:
        batch_op.create_index('idx_rotation_exception_tenant_floor_date', ['tenant_id', 'floor', 'exception_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_rotation_exception_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('room_rotation_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_settings_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rotation_settings_id'], ['room_rotation_settings.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_rotation_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_rotation_order_rotation_settings_id'), ['rotation_settings_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_rotation_order_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_rotation_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_rotation_order_team_id'))
        batch_op.drop_index(batch_op.f('ix_room_rotation_order_rotation_settings_id'))

    op.drop_table('room_rotation_order')
    with op.batch_alter_table('room_rotation_exception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_rotation_exception_tenant_id'))
        batch_op.drop_index('idx_rotation_exception_tenant_floor_date')

    op.drop_table('room_rotation_exception')
    with op.batch_alter_table('room_rotation_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_rotation_settings_tenant_id'))
        batch_op.drop_index('idx_rotation_settings_tenant_floor')

    op.drop_table('room_rotation_settings')
    # ### end Alembic commands ###
